version: '3.9'
services:
  api:
    container_name: expenses_api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: on-failure
    command: sh -c "python manage.py migrate && python manage.py loaddata ./fixtures/Category.json && python manage.py loaddata ./fixtures/Currency.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/usr/src/api
      - static:/usr/src/api/static
    env_file:
      - .env
    depends_on:
      - postgres

  receipts:
    container_name: expenses_receipts
    build:
      context: ./receipts
      dockerfile: Dockerfile.dev
    restart: on-failure
    command: python -m app
    volumes:
      - ./receipts:/usr/src/receipts
    env_file:
      - .env

  frontend:
    container_name: expenses_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ./frontend:/usr/src/app

  nginx:
    container_name: expenses_nginx
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/usr/share/nginx/html/static

  redis:
    container_name: expenses_redis
    image: redis:latest

  postgres:
    container_name: expenses_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static:
  postgres_data:
