version: '3.9'
services:
  api:
    container_name: expenses_api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/api
      - static:/usr/src/api/static
    env_file:
      - .env

  receipts:
    container_name: expenses_receipts
    build:
      context: ./receipts
      dockerfile: Dockerfile.dev
    restart: on-failure
    command: python -m app
    volumes:
      - ./receipts:/usr/src/receipts
    env_file:
      - .env

  frontend:
    container_name: expenses_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ./frontend:/usr/src/app

  nginx:
    container_name: expenses_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/usr/share/nginx/html/static

  redis:
    container_name: expenses_redis
    image: redis:latest

volumes:
  static:
