version: '3.9'
services:
  api:
    build:
      context: ./backend
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8080
    env_file:
      - .env
