# Generated by Django 4.1.3 on 2023-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='$', max_length=1),
            preserve_default=False,
        ),
    ]
