# Generated by Django 4.1.3 on 2023-01-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
