# Generated by Django 4.1.3 on 2023-01-16 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 11, 33, 52, 672530, tzinfo=datetime.timezone.utc)),
        ),
    ]
